---
server:
  port: 8888
spring:
  cloud:
    config:
      server:
       git:
        uri: https://github.com/Moussi/toll-app-config # default
          #username: abc
          #password: abc
        search-paths:
          - 'station*'
